import "~/styles/globals.css"

import { Inter } from "next/font/google"

import { cn } from "~/lib/utils"

import { ThemeProvider } from "./theme-provider"

const inter = Inter({
  subsets: ["latin"],
})

// set time to shanghai
process.env.TZ = "Asia/Shanghai"

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-Hans" suppressHydrationWarning className="h-full">
      <body className={cn("h-full", inter.className)}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}
